version: '3'

services:
  glances:
    image: nicolargo/glances:latest-alpine
    container_name: glances
    hostname: docker-proxmox
    restart: always
    pid: host
    #ports:
    #  - 61208:61208
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - "GLANCES_OPT=-w"
    network_mode: bridge
