---
version: "3.8"
services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy
    environment:
      - PUID=1000
      - PGID=1000
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=<EXTERNAL-DOMAIN>
      # Optional:
      # - PASSWORD=foobar123
      - WG_PORT=<EXTERNAL-PORT>
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=<PRIMARYPIHOLE>,<SECONDARYPIHOLE>
      - WG_MTU=1420
      # - WG_PERSISTENT_KEEPALIVE=30
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      ##- WG_POST_UP=iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o ens3 -j MASQUERADE
      #- WG_POST_UP=
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      ##- WG_POST_DOWN=iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o ens3 -j MASQUERADE
      #- WG_POST_DOWN=
    volumes:
      - ./config:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    network_mode: bridge
