version: "3"

services:
  shlink-app:
    image: shlinkio/shlink:stable
    restart: always
    container_name: shlink-backend
    environment:
      - TZ="Europe/Berlin"
      - DEFAULT_DOMAIN=<shlink.example.com> #no http/https. no trailing slash
      - IS_HTTPS_ENABLED=false
      - GEOLITE_LICENSE_KEY=<GEOLITE-API-TOKEN>
      - DB_DRIVER=maria
      - DB_USER=shlink
      - DB_NAME=shlink
      - DB_PASSWORD=password #change this
      - DB_HOST=shlink-db
    depends_on:
      shlink-db:
        condition: service_healthy
    #ports:
    #  - 8080:8080
    network_mode: bridge
    healthcheck:
      test: curl --fail http://localhost:8080/rest/health || exit 1
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 5s

  shlink-db:
    image: mariadb:10.8
    restart: always
    container_name: shlink-database
    environment:
      - MARIADB_ROOT_PASSWORD=password #change this
      - MARIADB_DATABASE=shlink
      - MARIADB_USER=shlink
      - MARIADB_PASSWORD=password #change this
    volumes:
      - ./db-data:/var/lib/mysql
    network_mode: bridge
    healthcheck:
      test: ["CMD-SHELL", "mysql -h localhost -u $$MARIADB_USER -p$$MARIADB_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 10

  shlink-web-client:
    image: shlinkio/shlink-web-client:stable
    restart: always
    container_name: shlink-gui
    environment:
      - SHLINK_SERVER_URL=https://shlink.example.com
      - SHLINK_SERVER_API_KEY=<SHLINK-SERVER-API-KEY>
      - SHLINK_SERVER_NAME=Homelab
    volumes:
      - ./servers.json:/usr/share/nginx/html/servers.json #this file will be generated automatically
    depends_on:
      shlink-app:
        condition: service_healthy
    #ports:
    #  - 80:80
    network_mode: bridge
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
