---

services:
  monitoring:
    image: checkmk/check-mk-raw:2.4.0-latest
    container_name: checkmk
    ports:
      - "8000:8000" # checkmk agent
      - "5000:5000" # webserver
      - "162:162/udp"
    environment:
      - TZ=Europe/Berlin
      - CMK_PASSWORD=passwort123 # admin password for user cmkadmin
      - CMK_SITE_ID=homelab
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sites:/omd/sites:rw
    restart: always
