---
version: "2.1"
services:
  grafana:
    image: influxdb:1.8
    container_name: influxdb
    user: "1000:1000"
    ports:
      - 8086:8086
    volumes:
      - ./data:/var/lib/influxdb
      - ./backup:/mnt/backup
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      - TZ=Europe/Berlin
      - HOME=/var/lib/influxdb
      #- INFLUXDB_DB=db0
      #- INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      #- INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    restart: always
    healthcheck:
      test: curl --fail http://localhost:8086/ping || exit 1
      interval: 10s
      retries: 10
      #start_period: 60s
      timeout: 5s
    network_mode: bridge
