version: '3'
services:
  unifi-poller:
    image: ghcr.io/unpoller/unpoller:latest
    container_name: unpoller
    environment:
      # https://unpoller.com/docs/install/configuration/
      - UP_INFLUXDB_DB=unifi
      - UP_INFLUXDB_USER=
      - UP_INFLUXDB_PASS=
      - UP_INFLUXDB_URL=http://influxdb:8086
      #
      - UP_UNIFI_DEFAULT_USER=<USER>
      - UP_UNIFI_DEFAULT_PASS=<PASSWORD>
      - UP_UNIFI_DEFAULT_URL=https://<UDM-IP>
      - UP_POLLER_DEBUG=false
      - UP_UNIFI_DEFAULT_SAVE_DPI=false
      # interval defaut 30s
      - UP_INFLUXDB_INTERVAL=1m
      #
      - UP_PROMETHEUS_DISABLE=true
    restart: unless-stopped
    network_mode: bridge
