---
version: "2"
services:
  app:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    restart: always
    volumes:
      - ./app-data:/app/data
    #ports:
    #  - 3001:3001
    network_mode: bridge
